### ISSUE TITLE
Providing sndcpy automotor

### ISSUE THREAD

**Issue by Robihamanto** [madlymad/mac-scrcpy-app#4]
Really like your article on Medium and your script are super useful 🎉.

There is sound support also, here [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy).
Could you make about this automotor too?

Appreciate your work. Thanks a lot!

**Comment by madlymad** [comment]
I checked  it a bit and it seems that this is not directly supported by scrcpy but by a different tool called [sndcpy](https://github.com/rom1v/sndcpy). 

According to sndcpy page it can start from console via `sndcpy <serial>` so feel free to fork the repository and modify this 
line https://github.com/madlymad/mac-scrcpy-app/blob/main/scripts/run_scrcpy.sh#L16.
In that line `$d` is the device serial number so changing this line to `sndcpy $d` will start the other application.
In case you want to start both apps then just add the new line and also keep the old one.

If you do not start from scratch you can open the macOS Application with the Automator app and do the modifications there.

In case you need further help let me know.
